import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Format date for display
const formatDate = (timestamp) => {
  return new Date(timestamp).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
};

// Format date for filenames
const getFileDate = () => {
  const now = new Date();
  return now.toISOString().split('T')[0]; // YYYY-MM-DD
};

// Generate PDF report
export const exportToPDF = (logs, dateRange = 'All Time') => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.setTextColor(30, 58, 138); // Blue-900
  doc.text('Symptom Tracking Report', 14, 22);

  // Subtitle with date range
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Report Period: ${dateRange}`, 14, 30);
  doc.text(`Generated: ${formatDate(new Date())}`, 14, 36);
  doc.text(`Total Entries: ${logs.length}`, 14, 42);

  // Summary statistics
  if (logs.length > 0) {
    // Group by symptom and calculate averages
    const symptomStats = {};
    logs.forEach(log => {
      if (!symptomStats[log.symptomName]) {
        symptomStats[log.symptomName] = {
          name: log.symptomName,
          category: log.category,
          count: 0,
          totalSeverity: 0,
          maxSeverity: 0,
        };
      }
      symptomStats[log.symptomName].count++;
      symptomStats[log.symptomName].totalSeverity += log.severity;
      symptomStats[log.symptomName].maxSeverity = Math.max(
          symptomStats[log.symptomName].maxSeverity,
          log.severity
      );
    });

    // Summary table
    doc.setFontSize(14);
    doc.setTextColor(30, 58, 138);
    doc.text('Summary by Symptom', 14, 54);

    const summaryData = Object.values(symptomStats).map(stat => [
      stat.name,
      stat.category,
      stat.count.toString(),
      (stat.totalSeverity / stat.count).toFixed(1),
      stat.maxSeverity.toString(),
    ]);

    doc.autoTable({
      startY: 58,
      head: [['Symptom', 'Category', 'Occurrences', 'Avg Severity', 'Max Severity']],
      body: summaryData,
      theme: 'striped',
      headStyles: { fillColor: [30, 58, 138] },
      styles: { fontSize: 9 },
    });

    // Detailed log table
    const detailStartY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setTextColor(30, 58, 138);
    doc.text('Detailed Log Entries', 14, detailStartY);

    const detailData = logs.map(log => [
      formatDate(log.timestamp),
      log.symptomName,
      log.severity.toString(),
      log.notes || '-',
    ]);

    doc.autoTable({
      startY: detailStartY + 4,
      head: [['Date/Time', 'Symptom', 'Severity', 'Notes']],
      body: detailData,
      theme: 'striped',
      headStyles: { fillColor: [30, 58, 138] },
      styles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 35 },
        2: { cellWidth: 20 },
        3: { cellWidth: 'auto' },
      },
    });
  } else {
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text('No symptom entries found for this period.', 14, 54);
  }

  // Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
        'Generated by Veteran Symptom Tracker',
        14,
        doc.internal.pageSize.height - 10
    );
    doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.width - 30,
        doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  doc.save(`symptom-report-${getFileDate()}.pdf`);
};

// Generate CSV export
export const exportToCSV = (logs) => {
  if (logs.length === 0) {
    alert('No entries to export');
    return;
  }

  // CSV headers
  const headers = ['Date', 'Time', 'Symptom', 'Category', 'Severity', 'Notes'];

  // Format data rows
  const rows = logs.map(log => {
    const date = new Date(log.timestamp);
    return [
      date.toLocaleDateString('en-US'),
      date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }),
      `"${log.symptomName}"`,
      `"${log.category}"`,
      log.severity,
      `"${(log.notes || '').replace(/"/g, '""')}"`, // Escape quotes in notes
    ];
  });

  // Combine headers and rows
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');

  // Create and download file
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `symptom-log-${getFileDate()}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};